### ISSUE TITLE
Support for addtional custom databases

### ISSUE THREAD

**Issue by pkubat** [ua-parser/uap-ruby#11]
The ability to support more that one regexes database file.  (regexes should be any array of filenames)

The thought here is that one file would be the "standard" from https://github.com/tobie/ua-parser/blob/master/regexes.yaml and another might contain "custom" user agents.  They could be appended to the standard by sections; user_agent_parsers, os_parsers,  ,device_parsers.

The files should be "loaded" in order.

Also see the request for Logstash: https://logstash.jira.com/browse/LOGSTASH-1323

**Comment by wallin** [comment]
@pkubat I realize this has been a while. Do you think you'll be able to do a PR with the requested functionality?
