### ISSUE TITLE
Git submodule should point to uap-core

### ISSUE THREAD

**Issue by ajvondrak** [ua-parser/uap-ruby#20]
The git submodule in this repo still points at https://github.com/tobie/ua-parser, but per the README:

> # ua-parser has moved
> 
> This project has moved to a new project space [ua-parser](https://github.com/ua-parser), separating the regexes from the parsers for the different languages into their own repos:
> 
> * [uap-core](https://github.com/ua-parser/uap-core) : The regex file necessary to build language ports of Browserscope's user agent parser.

I figure this will probably be fixed the next time the gem is bumped to get an updated database (BTW, uap-core *has* updated since the last version of this gem), but I thought I'd make this issue explicit just in case. ;)

**Comment by mdb** [comment]
Is there any update on this issue? At-a-glance assessment suggests that `uap-ruby` is somewhat outdated in UA parsing.

**Comment by toolmantim** [comment]
@mdb @ajvondrak I don't personally use this gem now and is currently unmaintained. There's also been a pretty open policy for contributors and maintainers, happy for someone to take the reigns.

Let me know and I can add the relevant creds.

**Comment by wallin** [comment]
@toolmantim Hi! I'd also like this project to be kept updated and I'd be happy to contribute

**Comment by wallin** [comment]
ping @toolmantim.
I'd be happy to take the reigns here

**Comment by toolmantim** [comment]
Sorry for the delay @wallin! I've just added you as a team member on Github and a gem maintainer.

I've also added @rejeep, @deverton and @jnunemaker who were previously on the Github repo also, before they were all migrated here.

Also feel free to send through pull requests and I'm happy to review if you need.

**Comment by wallin** [comment]
Awesome, thanks! I started update the source to `uap-core` on a branch:
https://github.com/ua-parser/uap-ruby/tree/update-ua-parser-source
Need to fix the tests as well
