### ISSUE TITLE
Headless Chrome is reported as Safari

### ISSUE THREAD

**Issue by statico** [ua-parser/uap-ruby#29]
This:

```
$ irb
jruby-9.1.8.0 :001 > require 'user_agent_parser'
 => true
jruby-9.1.8.0 :002 > ua = UserAgentParser.parse('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome Safari/537.36')
 => #<UserAgentParser::UserAgent Safari (Linux) (Other)>
jruby-9.1.8.0 :003 > ua.to_s
 => "Safari"
jruby-9.1.8.0 :004 > ua.version
 => nil
```

The context is that we're using [Capybara and headless Chrome](http://blog.faraday.io/headless-chromium-with-capybara-and-selenium-webdriver/) to drive some testing. We record the parsed user agent in our tests and we get `Safari` instead of something Chrome-like.

**Comment by wallin** [comment]
@statico, thanks for reporting. HeadlessChrome should be handled in the latest uap-core rules, so we need to update subrepo and release a new gem. I'll look into it, but feel free to create a PR if you beat me to it.

**Comment by wallin** [comment]
I just released `2.3.1` which uses the latest rules database

```
2.3.1 :001 > require 'user_agent_parser'
 => true
2.3.1 :002 > ua = UserAgentParser.parse('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome Safari/537.36')
 => #<UserAgentParser::UserAgent HeadlessChrome (Linux) (Other)>
2.3.1 :003 > ua.to_s
 => "HeadlessChrome"
2.3.1 :004 > ua.version
 => nil
```
Version is still reported as `nil` though

**Comment by statico** [comment]
Thank you for this!

cc @delaneyparker

**Comment by toolmantim** [comment]
Thanks for doing an update of the gem @wallin!
